# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 737ac798239c605d8b480edbc3f2b8b52885b75346b0ff0d45a47f7887f00d008080d058f6e871a86c8de9c940cf760faec5a5d8b865a5546758c24c1a3a1173

test:
  secret_key_base: e553fcb5ab0ffd08e748e12bf6670b3d7802f30cf71f0f9193a3900d2016814db515e7364d3e25686700a81948ce250e64f276eb829a42da176d3b313696fb44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
